### PR TITLE
add more supported voices in models.py

### PR DESCRIPTION
**Pull request by xwang-otterai**
from realtime api doc: https://platform.openai.com/docs/api-reference/realtime-client-events

>The voice the model uses to respond. Supported voices are ash, ballad, coral, sage, and verse (also supported but not recommended are alloy, echo, and shimmer; these voices are less expressive). Cannot be changed once the model has responded with audio at least once.

## Purpose
add add more supported voices in Voice model in models.py

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code
Use the python client and use one of the newly added supported voice: [ash, ballad, coral, sage, and verse]

## What to Check
Verify that the following are valid

new voices work

### CODE REVIEW

**Comment by xwang-otterai** [comment]
@glecaros @trrwilson Can you please review? Thanks!

**Comment by manu3b1** [comment]
With this patch, after adding one the new voices (ash) in client_sample.py:

```
async def run(client: RTClient, audio_file_path: str, out_dir: str):
    print("Configuring Session...", end="", flush=True)
    await client.configure(
        turn_detection=ServerVAD(threshold=0.5, prefix_padding_ms=300, silence_duration_ms=200),
        input_audio_transcription=InputAudioTranscription(model="whisper-1"),
        voice="ash",
```
I get this error:

```
$ python client_sample.py input/arc-easy-q237-tts.wav output/ azure
Configuring Session...Traceback (most recent call last):
  File "/home/renault/Openai/aoai-realtime-audio-sdk/python/samples/client_sample.py", line 206, in <module>
    asyncio.run(with_azure_openai(file_path, out_dir))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/renault/Openai/aoai-realtime-audio-sdk/python/samples/client_sample.py", line 172, in with_azure_openai
    await run(client, audio_file_path, out_dir)
  File "/home/renault/Openai/aoai-realtime-audio-sdk/python/samples/client_sample.py", line 149, in run
    await client.configure(
  File "/home/renault/Openai/aoai-realtime-audio-sdk/python/samples/venv/lib/python3.10/site-packages/rtclient/__init__.py", line 686, in configure
    raise RealtimeException(message.error)
rtclient.RealtimeException: Invalid value: 'ash'. Supported values are: 'amuch', 'dan', 'elan', 'marilyn', 'meadow', 'breeze', 'cove', 'ember', 'jupiter', 'alloy', 'echo', and 'shimmer'.
```
with "gpt-4o-realtime-preview" deployment.

**Comment by xwang-otterai** [comment]
@manu3b1 I didn't test with Azure OpenAI. @glecaros @trrwilson do you know if OpenAI and Azure's OpenAI  support different voices for Realtime API?

**Comment by allanc92** [comment]
@xwang-otterai the realtime model in Azure OpenAI does not currently support ash, ballad, coral, sage, and verse. Stay tuned as we continue to update the model and add new features, including additional voices!

**Review by glecaros — APPROVED** [review]
Thanks for the contribution, in my next PR I'll update javascript to also include these.

**Pull request merged**
